# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('office_phone', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=30)),
                ('resident_id', models.CharField(max_length=50)),
                ('resident_file', models.ImageField(blank=True, upload_to='resident_file/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
