# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171030_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_filename',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, upload_to='static/uploads/project_file/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
