# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171030_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='main_file',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='start_frame',
            field=models.IntegerField(default=0),
        ),
    ]
